#!/usr/bin/env bash
# Bash script that configures a new ubuntu machine and install nginx

sudo apt-get update
sudo apt-get -y install nginx
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo service nginx restart
