#!/usr/bin/env bash
# Bash script to Install and configure HAproxy on your lb-01 server.
sudo apt-get update
sudo apt-get -y install haproxy
sudo echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo echo "
frontend http
	bind *:80
	mode http
	default_backend back
backend back
	balance roundrobin
        server 12847-web-01 100.26.196.115:80 check
        server 12847-web-02 3.239.59.232:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
