#!/usr/bin/env bash
# This script kills the infinity and beyond program using sigkill signal

# Gets the PID of the program
id=$(pgrep "bash ./4-to_infinity_and_beyond" -f)

# Terminate the infinity process
if [ -n "$id" ]
then
    kill -15 "$id"
fi
