#!/usr/bin/env bash
# This script diaplays Best School 10 times
#+ but after the 9th iteration displays Hi
n=1
while true; do
    echo "Best School"
    if (("$n" == 9)); then
        echo "Hi"
    elif (("$n" == 10)); then
        break
    fi

     ((n+=1))
done
