#!/usr/bin/env bash
#Bash script that gives you information about the school file
FILE="./school"
if [ -e "$FILE" ]; then
    printf "%s\n" "school file exists"
    if [ -s "$FILE" ]; then
	printf "%s\n" "school file is not empty"
    else
	printf "%s\n" "school file is empty"
    fi
    if [ -f "$FILE" ]; then
	printf "%s\n" "school is a regular file"
    fi
else
    printf "%s\n" "school file does not exist"
fi
